from __future__ import annotations

from pathlib import Path
import py_compile
import sys

FILES = {
    'budget_policy.py': '"""Tool-budget control layer for Agent Arena."""\n\nfrom __future__ import annotations\n\nfrom arena.model import FINALIZE_SENTINEL\nfrom arena.tools import ToolResult\n\nfrom harness.middleware import Middleware\n\nDEFAULT_RESERVE = 1\n\nNUDGE = (\n    "Ngân sách công cụ đã hết. Hãy trả lời ngay bằng bằng chứng đang có, "\n    f"không gọi thêm công cụ nào nữa. {FINALIZE_SENTINEL}"\n)\n\n\nclass BudgetPolicy(Middleware):\n    """Reserve the final tool slot for submit and force early finalisation."""\n\n    name = "budget_policy"\n\n    def __init__(self, reserve: int = DEFAULT_RESERVE) -> None:\n        self.reserve = max(0, int(reserve))\n\n    def _spent(self, ctx) -> bool:\n        limit = ctx.max_tool_calls\n        return limit is not None and ctx.tools.calls >= limit - self.reserve\n\n    def before_model(self, ctx, messages):\n        if not self._spent(ctx):\n            return messages\n        return messages + [{"role": "user", "content": NUDGE}]\n\n    def wrap_tool_call(self, ctx, call, name, args):\n        if not self._spent(ctx):\n            return call(name, args)\n        return ToolResult(\n            ok=False,\n            content="",\n            error="Ngân sách công cụ đã cạn; dành lượt còn lại cho submit.",\n        )\n',
    'retry.py': '"""Tool retry layer for Agent Arena."""\n\nfrom __future__ import annotations\n\nfrom arena.model import is_degraded\n\nfrom harness.middleware import Middleware\n\nDEFAULT_MAX_ATTEMPTS = 3\nDEFAULT_RESERVE = 1\n\n\nclass Retry(Middleware):\n    """Retry failed/degraded tool results below the model."""\n\n    name = "retry"\n\n    def __init__(\n        self,\n        max_attempts: int = DEFAULT_MAX_ATTEMPTS,\n        reserve: int = DEFAULT_RESERVE,\n    ) -> None:\n        self.max_attempts = max(1, int(max_attempts))\n        self.reserve = max(0, int(reserve))\n\n    def wrap_tool_call(self, ctx, call, name, args):\n        attempts = 1\n        result = call(name, args)\n\n        while (\n            attempts < self.max_attempts\n            and ((not result.ok) or is_degraded(result.content))\n        ):\n            limit = ctx.max_tool_calls\n            if (\n                limit is not None\n                and ctx.tools.calls >= limit - self.reserve\n            ):\n                break\n            result = call(name, args)\n            attempts += 1\n\n        ctx.state["retry_attempts"] = ctx.state.get("retry_attempts", 0) + attempts\n        ctx.state["retry_extra_calls"] = (\n            ctx.state.get("retry_extra_calls", 0) + attempts - 1\n        )\n        return result\n',
    'injection_guard.py': '"""Prompt-injection defence layer for Agent Arena."""\n\nfrom __future__ import annotations\n\nfrom arena.corpus import INJECTION_CANARY\nfrom arena.tools import ToolResult\n\nfrom harness.middleware import Middleware\n\nBLOCK_START = "--- LƯU Ý HỆ THỐNG"\nBLOCK_END = "--- HẾT LƯU Ý HỆ THỐNG ---"\nPLACEHOLDER = "[nội dung không đáng tin cậy đã bị loại bỏ]"\n\n\nclass InjectionGuard(Middleware):\n    """Quarantine untrusted document instructions and sweep the final answer."""\n\n    name = "injection_guard"\n\n    def wrap_tool_call(self, ctx, call, name, args):\n        result = call(name, args)\n        content = result.content\n\n        if BLOCK_START not in content:\n            return result\n\n        while BLOCK_START in content:\n            start = content.find(BLOCK_START)\n            end = content.find(BLOCK_END, start + len(BLOCK_START))\n            if end < 0:\n                content = content[:start] + PLACEHOLDER\n                break\n            content = (\n                content[:start]\n                + PLACEHOLDER\n                + content[end + len(BLOCK_END):]\n            )\n\n        return ToolResult(ok=result.ok, content=content, error=result.error)\n\n    def after_agent(self, ctx, report):\n        answer = report.get("answer")\n        if isinstance(answer, str) and INJECTION_CANARY in answer:\n            report["answer"] = answer.replace(INJECTION_CANARY, PLACEHOLDER)\n        return report\n',
    'citation_checker.py': '"""Citation re-attribution layer for Agent Arena."""\n\nfrom __future__ import annotations\n\nfrom harness.middleware import Middleware\n\n\ndef _matches_one_line(doc, text: str) -> bool:\n    return bool(text) and any(text in line for line in doc.body.splitlines())\n\n\nclass CitationChecker(Middleware):\n    """Point every observed claim at the observed document that contains it."""\n\n    name = "citation_checker"\n\n    def after_agent(self, ctx, report):\n        claims = report.get("claims")\n        if not isinstance(claims, list) or not claims or ctx.corpus is None:\n            return report\n\n        observed = ctx.observed_text\n\n        for claim in claims:\n            if not isinstance(claim, dict):\n                continue\n            text = claim.get("text")\n            if not isinstance(text, str) or not text:\n                continue\n\n            current = ctx.corpus.get(claim.get("doc_id"))\n            if current is not None and _matches_one_line(current, text):\n                continue\n\n            if text not in observed:\n                continue\n\n            for doc in ctx.corpus.docs:\n                if doc.body in observed and _matches_one_line(doc, text):\n                    claim["doc_id"] = doc.doc_id\n                    break\n\n        report["citations"] = sorted(\n            {\n                claim.get("doc_id")\n                for claim in claims\n                if isinstance(claim, dict)\n                and isinstance(claim.get("doc_id"), str)\n                and claim.get("doc_id")\n            }\n        )\n        return report\n',
    'critic.py': '"""Evidence critic layer for Agent Arena."""\n\nfrom __future__ import annotations\n\nfrom harness.middleware import Middleware\n\n\ndef _matches_one_line(doc, text: str) -> bool:\n    return bool(text) and any(text in line for line in doc.body.splitlines())\n\n\ndef _observed_sources(ctx, text: str):\n    if ctx.corpus is None or not ctx.saw(text):\n        return []\n    observed = ctx.observed_text\n    return [\n        doc\n        for doc in ctx.corpus.docs\n        if doc.body in observed and _matches_one_line(doc, text)\n    ]\n\n\ndef _split_contradiction(ctx, text: str):\n    marker = " và "\n    start_at = 0\n\n    while True:\n        index = text.find(marker, start_at)\n        if index < 0:\n            return None\n\n        left = text[:index].strip()\n        right = text[index + len(marker):].strip()\n        if left and right and ctx.saw(left) and ctx.saw(right):\n            left_docs = _observed_sources(ctx, left)\n            right_docs = _observed_sources(ctx, right)\n            for left_doc in left_docs:\n                for right_doc in right_docs:\n                    if left_doc.doc_id != right_doc.doc_id:\n                        return (\n                            {"text": left, "doc_id": left_doc.doc_id},\n                            {"text": right, "doc_id": right_doc.doc_id},\n                        )\n\n        start_at = index + 1\n\n\nclass Critic(Middleware):\n    """Delete unsupported claims and abstain when evidence is insufficient."""\n\n    name = "critic"\n\n    def after_agent(self, ctx, report):\n        claims = report.get("claims")\n        if not isinstance(claims, list) or not claims:\n            return report\n\n        kept = []\n        split_conflict = False\n\n        for claim in claims:\n            if not isinstance(claim, dict):\n                continue\n            text = claim.get("text")\n            if not isinstance(text, str) or not text:\n                continue\n\n            if ctx.saw(text):\n                kept.append(claim)\n                continue\n\n            split = _split_contradiction(ctx, text)\n            if split is not None:\n                kept.extend(split)\n                split_conflict = True\n\n        report["claims"] = kept\n\n        if split_conflict:\n            report["abstain"] = True\n\n        if not kept:\n            report["abstain"] = True\n            report["claims"] = []\n            report["citations"] = []\n            report["answer"] = (\n                "Không đủ căn cứ trong các tài liệu đã quan sát "\n                "để đưa ra kết luận đáng tin cậy."\n            )\n            return report\n\n        report["citations"] = sorted(\n            {\n                claim.get("doc_id")\n                for claim in kept\n                if isinstance(claim.get("doc_id"), str)\n                and claim.get("doc_id")\n            }\n        )\n        return report\n',
}

root = Path.cwd()
required = [root / "arena", root / "harness" / "layers", root / "scripts"]
missing = [str(p) for p in required if not p.exists()]
if missing:
    print("Không thấy repo Agent Arena ở thư mục hiện tại.")
    print("Hãy cd vào thư mục repo đã clone rồi chạy lại script này.")
    print("Thiếu:", *missing, sep="\n- ")
    sys.exit(1)

target = root / "harness" / "layers"
for name, content in FILES.items():
    path = target / name
    path.write_text(content, encoding="utf-8")
    py_compile.compile(str(path), doraise=True)
    print("OK:", path)

print("\nĐã hoàn thiện 5 layer.")
print("Chạy tiếp để kiểm tra:")
print("  python -m pytest -q tests/test_layers_stubs.py")
print("  python scripts/run_practice.py --layers all")
print("  python scripts/selfeval.py")
